### ISSUE TITLE
Padronização a Aviso Legal (Disclaimer) do @HXL-CPLP quanto à citação de nomes de outras organizações

### ISSUE THREAD

**Issue by fititnt** [HXL-CPLP/forum#11]
Referências rápidas:

- **Questões**:
  - **Documentação mínima do que é a organização @HXL-CPLP #1** (motivo: de certa forma este ponto é uma forma do que **não** é o HXL-CPLP)
  - **Produto Mínimo Viável de tradução de "Princípios e padrões humanitários (higuide/Elrha)" #7** (motivo: potencialmente ao termos aviso legal, serve também como oportunidade para desenvolvedores que resolvam fazer aplicações humanitárias entendam que uso de certos logos seria restrito)
- **Usando como referência o que ocorre na comunidade Joomla!®**
  - https://docs.joomla.org/Joomla:Trademarks
  - https://tm.joomla.org/disclaimers.html
- **Termos de uso de simbolos da Cruz Vermelha**
  - https://www.icrc.org/en/copyright-and-terms-use

---

Fato: As pessoas por trás do @HXL-CPLP não são endossados ou afiliados com as organizações que eventualmente forem citadas nas documentações e repositórios. Não obstante, mesmo que não haja um aviso específico em https://hxlstandard.org/ **preventivamente faz sentido deixarmos mais explicito para evitar até mesmo percepção errada de pessoas ou veículos de mídia**.

Uma motivação adicional é que nossa abordagem explicita sobre uso de marcas pode implicitamente educar o uso por ferramentas que, ao se basear no HXL e queiram fazer algo para organizações humanitárias, possam também estar cientes de que devem fazer uso mais restritivo.

**Comment by fititnt** [comment]
Podemos usar este por enquanto:

---

Tanto o site <https://padrao-hxl.etica.ai> como a organização no GitHub <https://github.com/HXL-CPLP> e seus projetos são realizações voluntárias do **Grupo de Usuários do Padrão HXL da Comunidade dos Países de Língua Portuguesa** e, ainda que possa haver colaboração ou uso de conteúdo, **não somos afiliados ou endossados por HXLStandard.org, OCHA, IFRC e afins**.

---

```markdown
Tanto o site <https://padrao-hxl.etica.ai> como a organização no GitHub <https://github.com/HXL-CPLP> e seus projetos são realizações voluntárias do **Grupo de Usuários do Padrão HXL da Comunidade dos Países de Língua Portuguesa** e, ainda que possa haver colaboração ou uso de conteúdo, **não somos afiliados ou endossados por HXLStandard.org, OCHA, IFRC e afins**.
```

**Comment by fititnt** [comment]
Com quebra de linha

```markdown
Tanto o site <https://padrao-hxl.etica.ai> como a organização no GitHub
<https://github.com/HXL-CPLP> e seus projetos são realizações voluntárias do
**Grupo de Usuários do Padrão HXL da Comunidade dos Países de Língua
Portuguesa** e, ainda que possa haver colaboração ou uso de conteúdo,
**não somos afiliados ou endossados por HXLStandard.org, OCHA, IFRC e afins**.
```

**Comment by fititnt** [comment]
Faltou os em inglês

- https://github.com/HXL-CPLP/internationalization-tips
- https://github.com/HXL-CPLP/internationalization-tips-samples

**Comment by anabarcellos** [comment]
The website padrao-hxl.etica.ai and the 
@ HXL-CPLP GitHub projects were made by the volunteer "HXL Standard for the Community of Portuguese Speaking Countries User Group", not affiliated or endorsed by HXLStandard.org, OCHA, IFRC and similar, although there may be collaboration or use of content.

**Comment by GustavoDuregger** [comment]
Aviso legal foi adicionado em todos os repositórios
