### ISSUE TITLE
Produto Mínimo Viável do site de divulgação do @HXL-CPLP

### ISSUE THREAD

**Issue by fititnt** [HXL-CPLP/forum#12]
Referências rápidas:

- **URL do site**: https://padrao-hxl.etica.ai/
- **Tecnologia usada**:
  - CMS Joomla!®
  - https://www.joomla.org/

---

Esta questão, que definitivamente deve envolver diversas outras, é sobre eventualmente termos o primeiro Produto Mínimo Viável de um site voltado para divulgação do publico em geral.

**Comment by anabarcellos** [comment]
Em progresso. Início 24/04/2020 às 20h 
[Kanbam do Site](https://github.com/orgs/HXL-CPLP/projects/2?add_cards_query=is%3Aopen)
