### ISSUE TITLE
PMV de pasta no Google Drive com documentos de exemplo usando hashtags HXL, preferencialmente no contexto da CPLP

### ISSUE THREAD

**Issue by fititnt** [HXL-CPLP/forum#14]
Referências rápidas:

- **Pasta no Google Drive do @HXL-CPLP #6**
- https://github.com/HXLStandard/hxl-cookbook 
  - Usa exemplos a nível internacional
- https://github.com/SimonbJohnson/quickX3
  - Usa esta planilha como exemplo https://docs.google.com/spreadsheets/d/1R9zfMTk7SQB8VoEp4XK0xAWtlsQcHgEvYiswZsj9YA4/edit#gid=0

---

Questão sobre Produto Mínimo Viável de pasta com documentos de exemplo usando hashtags HXL, preferencialmente com exemplos práticos usados na CPLP.

**Comment by fititnt** [comment]
https://drive.google.com/drive/u/1/folders/1S1ccCekK0QPaAB8NYyzbNyvaFDdSuiYu

**Comment by GustavoDuregger** [comment]
Conteúdo em https://drive.google.com/drive/u/1/folders/1S1ccCekK0QPaAB8NYyzbNyvaFDdSuiYu
