### ISSUE TITLE
Motivação Inicial da Formação do HXL-CPLP: UNESCO Global virtual Hackathon 2020 (TL;DR: time de pré-formação não foi qualificado)

### ISSUE THREAD

**Issue by fititnt** [HXL-CPLP/forum#16]
Referências rápidas

- **Proposta do pré-time de formação do HXL-CPLP no hackathon**
    - [EticaAI_UNESCO-Global-Hackathon_1a-submissao-2020-04-15.pdf](https://github.com/HXL-CPLP/forum/files/4534371/EticaAI_UNESCO-Global-Hackathon_1a-submissao-2020-04-15.1.pdf)
    - <https://drive.google.com/drive/folders/1mm8IlPKtY7-EFjwTMYnpUcg6YMbgnPny>
- **Lista de projetos que, oficialmente, foram qualificados para participar do hackathon**
  - <https://drive.google.com/drive/u/1/folders/1EmKtW2XDnB6B1dEUCExfANwbUFWH00Hs> 
    - Nota: oficialmente o time de pré-formação do HXL-CPLP não foi qualificado para participar no hackathon
- **Milestone**
  - <https://github.com/HXL-CPLP/forum/milestone/1>
- **Projeto**
  - <https://github.com/orgs/HXL-CPLP/projects/1>
- Página do evento:
    - [**UNESCO Global virtual Hackathon 2020**](https://en.unesco.org/events/codethecurve-hackathon)
  - Copia de segurança da página do evento: <http://archive.vn/OqiLA>

A motivação inicial para formação do @HXL-CPLP foi proposta enviada ao [**UNESCO Global virtual Hackathon 2020**](https://en.unesco.org/events/codethecurve-hackathon) (copia de segurança da página do evento: <http://archive.vn/OqiLA>).

Ainda que o grupo não tenha sido qualificado até mesmo para fazer parte do hackathon e participar com os demais, 4 dos dos 6 membros optou por ir adiante.

### Motivação

Não ser selecionado para um hackathon que, no fundo, está lidando com inovação humanitária, mas aplica pensamento de hackathon tradicional, não significa que a proposta tenha sido ruim.

Possivelmente depois do hackathon vamos pode ter mais material explicando nossa participação.

**Comment by fititnt** [comment]
Feito! Hackathon encerrado!

cc @anabarcellos @cdiegosr @GustavoDuregger

**Comment by GustavoDuregger** [comment]
😎
