### ISSUE TITLE
PMV de Badge para projetos que implementam o padrão HXL

### ISSUE THREAD

**Issue by GustavoDuregger** [HXL-CPLP/forum#17]

**Comment by fititnt** [comment]
Referencias de badges do open data https://osf.io/tvyxz/wiki/1.%20View%20the%20Badges/

**Comment by fititnt** [comment]
Talvez podemos usar isso por enquanto

[![https://img.shields.io/badge/Standard-HXL-%23F26459](https://img.shields.io/badge/Standard-HXL-%23F26459)](https://hxlstandard.org/)

O tom de vermelho parece ser #F26459

```
[![https://img.shields.io/badge/Standard-HXL-%23F26459](https://img.shields.io/badge/Standard-HXL-%23F26459)](https://hxlstandard.org/)
```

**Comment by fititnt** [comment]
Sobre badges que pegam licença ja do repositório:

![GitHub](https://img.shields.io/github/license/HXL-CPLP/forum)

```
![GitHub](https://img.shields.io/github/license/HXL-CPLP/forum)
```

**Comment by fititnt** [comment]
Exemplo com stars de GitHub

![GitHub stars](https://img.shields.io/github/stars/HXL-CPLP/exemplos-praticos-usando-hashtags-padrao-hxl?style=social)

```
![GitHub stars](https://img.shields.io/github/stars/HXL-CPLP/exemplos-praticos-usando-hashtags-padrao-hxl?style=social)
```

**Comment by fititnt** [comment]
Alterado para ter o texto alternativo correto (usado por leitores de tela e mecanismos de busca)

Talvez podemos usar isso por enquanto

[![Standard HXL](https://img.shields.io/badge/Standard-HXL-%23F26459)](https://hxlstandard.org/)

O tom de vermelho parece ser #F26459

```
[![Standard HXL](https://img.shields.io/badge/Standard-HXL-%23F26459)](https://hxlstandard.org/)
```

**Comment by fititnt** [comment]
Banner padrão

[![Grupo de Usuários do Padrão HXL da Comunidade dos Países de Língua Portuguesa](https://hxl.etica.ai/img/banner-hxl-cplp.png)](https://padrao-hxl.etica.ai/)

```
[![Grupo de Usuários do Padrão HXL da Comunidade dos Países de Língua Portuguesa](https://hxl.etica.ai/img/banner-hxl-cplp.png)](https://padrao-hxl.etica.ai/)
```

**Comment by fititnt** [comment]
Atualização: faltou link para o repositório no GitHub Stars

[![GitHub stars](https://img.shields.io/github/stars/HXL-CPLP/hxl-cplp.github.io?style=social)](https://github.com/HXL-CPLP/hxl-cplp.github.io)

```
[![GitHub stars](https://img.shields.io/github/stars/HXL-CPLP/hxl-cplp.github.io?style=social)](https://github.com/HXL-CPLP/hxl-cplp.github.io)
```

**Comment by GustavoDuregger** [comment]
Padrão determinado para aplicações do badges no readme 🤪

```
# TITULO-TITULO-TITULO

> DESCRIÇÃO-DESCRIÇÃO-DESCRIÇÃO-DESCRIÇÃO-DESCRIÇÃO

[![Standard HXL](https://img.shields.io/badge/Standard-HXL-%23F26459)](https://hxlstandard.org/)
![GitHub](https://img.shields.io/github/license/HXL-CPLP/PROJETO-PROJETO-PRJETO-PROJETO-PROJETO)
[![GitHub stars](https://img.shields.io/github/stars/HXL-CPLP/PROJETO-PROJETO-PRJETO-PROJETO-PROJETO?style=social)](https://github.com/HXL-CPLP/PROJETO-PROJETO-PRJETO-PROJETO-PROJETO)

[![Grupo de Usuários do Padrão HXL da Comunidade dos Países de Língua Portuguesa](https://hxl.etica.ai/img/banner-hxl-cplp.png)](https://padrao-hxl.etica.ai/)
```
