### ISSUE TITLE
PMV de repositório + hotsite com referências sobre como melhorar internacionalização (foco em projetos que documentem o Padrão HXL)

### ISSUE THREAD

**Issue by fititnt** [HXL-CPLP/forum#19]
Referências rápidas:

- **Referências sobre implementação**
  - https://www.w3.org/International/questions/qa-html-language-declarations
-   https://achecker.ca/checker/suggestion.php?id=48
    - Can do the test again using https://achecker.ca/checker/
  - https://webaim.org/standards/wcag/checklist#sc3.1.1
    - See https://wave.webaim.org/report#/hxldash.com
  - https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
  - **Potential specification to NOT set English as default** 
    - https://www.w3.org/TR/i18n-html-tech-lang/#h2_overall
      - "Always declare the default language for text in the page using attributes on the html tag, unless the document contains content aimed at speakers of more than one language. more..."
- **Pontos de questão**
  - https://github.com/SimonbJohnson/quickX3/issues/73 (we can reuse the references from here)
  - https://github.com/HXLStandard/hxl-hashtag-chooser/pull/1 (this issue also have some references)
  - https://github.com/webiwg/feedback-from-translators (old project with "feedback from translators" on @WebIWG)

---

Ainda que no @HXL-CPLP estejamos fazendo tradução de muito conteúdo, existem certas questões que podem melhorar a eficiência de tradutores automáticos (como os embutidos em navegadores) para, por exemplo, saberem o que não é traduzível.

Este ponto é sobre criarmos um Produto Minimo Viável de repositório **em inglês** que possa ter referências rápidas sobre o tema.

**Comment by fititnt** [comment]
Aqui do `translate=no`

https://www.w3.org/International/questions/qa-translate-flag.en

**Comment by GustavoDuregger** [comment]
Feito!
Lançado em
https://github.com/HXL-CPLP/internationalization-tips/releases/tag/v1.0.0-alpha

Repositório: https://github.com/HXL-CPLP/internationalization-tips
