### ISSUE TITLE
PMV de repositório com amostras de problemas e soluções relacionadas a internacionalização

### ISSUE THREAD

**Issue by fititnt** [HXL-CPLP/forum#20]
Relacionado: **PMV de repositório + hotsite com referências sobre como melhorar internacionalização (foco em projetos que documentem o Padrão HXL) #19**

---

Prodoto Mínimo Viável de um repositório que contenha amostras de HTML que contenham exemplos sem as modificações, então, e os com modificações com potenciais melhorias.

Potencial URL:
- `internationalization-tips-samples`

**Comment by fititnt** [comment]
Temos que pegar algumas amostras daqui: https://hxlstandard.org/standard/1-1final/dictionary/

Problema é que o documento é muito grande. Talvez tenhamos que ter um HTML base, que obritagoriamente tenha o `<html lang="en">` como nos originais, mas o conteudo de antes vs depois

**Comment by GustavoDuregger** [comment]
Feito!
Lançado v1.0.0
https://github.com/HXL-CPLP/internationalization-tips-samples/releases/tag/v1.0.0-alpha

Site: https://hxl.etica.ai/internationalization-tips-samples/
Repositório: https://github.com/HXL-CPLP/internationalization-tips-samples
