### ISSUE TITLE
Produto Mínimo Viável de tradução de SimonbJohnson/im-tips, "50 Dicas para gerentes de informações humanitárias"

### ISSUE THREAD

**Issue by fititnt** [HXL-CPLP/forum#5]
Referências rápidas:
- **Repositório no GitHub**
  - https://github.com/SimonbJohnson/im-tips
- **Página publica do repositório original**
  - http://simonbjohnson.github.io/im-tips/
- **Licença**
  - MIT

---

Essa questão é sobre criarmos um fork e fazer tradução para Português do Brasil.

Nota: nesta primeira tradução não é preciso já incluir referências de vídeo tutoriais em português (a apresentação em certas partes aponta para vídeos do Youtube para explicar como usar MS Excel, por exemplo).

**Comment by GustavoDuregger** [comment]
Feito
Lançado v1.0.0
https://github.com/HXL-CPLP/dicas-para-gestores-de-informacao-humanitaria/releases/tag/v1.0.0

Site: https://hxl.etica.ai/dicas-para-gestores-de-informacao-humanitaria/
Repositório: https://github.com/HXL-CPLP/dicas-para-gestores-de-informacao-humanitaria
