### ISSUE TITLE
Produto Mínimo Viável de tradução de "Princípios e padrões humanitários (higuide/Elrha)" 

### ISSUE THREAD

**Issue by fititnt** [HXL-CPLP/forum#7]
Referências rápidas:

- **"HUMANITARIAN PRINCIPLES AND STANDARDS" (higuide/Elrha)**
  - <http://higuide.elrha.org/humanitarian-parameters/humanitarian-principles-and-standards/>

---

Um local que encontrei texto que poderíamos usar como base para um PMV de principios humanitários é o **"HUMANITARIAN PRINCIPLES AND STANDARDS" (higuide/Elrha)**.

### Motivação

Ainda que o @HXL-CPLP seja principalmente sobre um padrão (e o padrão da hashtags possa ser até reusado em contextos não só humanitários) existe a chance de pessoas da CPLP terem interesse em contribuir além do padrão, com aplicações. É nesse contexto que _alguma introdução rápida_ a princípios humanitários se torna importante. Outro ponto importante é que, em casos extremos, colaboradores que interagem em projetos que seguirem esse tipo de código de conduta podem acabar sendo atacados por _serem neutros_ (por exemplo, não se negarem a boicotar uma organização ou ações de uma organização) e esse tipo de material em português pode ajudar a reduzir a necessidade de que expliquem.

Vale lembra que, mesmo para quem quiser participar de projetos ou iniciativas que se guiem por esses princípios, isso **não afeta outros projetos**. Um ótimo exemplo é que é provável que ao menos parte do pessoal da CPLP que justamente tenha tendência de aderir inicialmente já participem de grupos tenham posições políticas fortes, e essas políticas não necessariamente estariam alinhadas com outros colaboradores. Na verdade a própria história do Padrão HXL é também uma evolução de um padrão que é flexível com divergências de grupos com definição de um vocabulário centralizado. 

#### Exemplo de tradução automática, não revisada (parte da página)

Origem: http://higuide.elrha.org/humanitarian-parameters/humanitarian-principles-and-standards/

> Os princípios humanitários centrais da **humanidade** , **imparcialidade** , **independência** e **neutralidade** são baseados no Direito Internacional Humanitário (como a Quarta Convenção de Genebra) e sustentam a definição do que constitui uma resposta 'humanitária' ( [OCHA, 2012](https://www.unocha.org/sites/dms/Documents/OOM-humanitarianprinciples_eng_June12.pdf) ).
> 
> -   **Humanidade:** O sofrimento humano deve ser tratado onde quer que seja encontrado. O objetivo da ação humanitária é proteger a vida e a saúde e garantir o respeito pelos seres humanos.
> -   **Neutralidade;** Os atores humanitários não devem tomar partido nas hostilidades ou se envolver em controvérsias de natureza política, racial, religiosa ou ideológica
> -   **Imparcialidade:** A ação humanitária deve ser realizada apenas com base nas necessidades, priorizando os casos mais urgentes de angústia e não fazendo distinção adversa com base na nacionalidade, raça, gênero, crença religiosa, classe ou opinião política.
> -   **Independência:** A ação humanitária deve ser autônoma dos objetivos políticos, econômicos, militares ou outros que qualquer ator possa ter em relação às áreas em que a ação humanitária está sendo implementada.
> 
> Esses princípios são a base para códigos de conduta, compromissos e padrões essenciais amplamente aceitos e integrados, incluindo o Código de Conduta do CICV, a Carta Humanitária e os Padrões Mínimos em Resposta Humanitária, e o Padrão Humanitário (CHS) sobre Qualidade e Responsabilidade.

**Comment by fititnt** [comment]
Potencialmente relacionado: https://corehumanitarianstandard.org/files/files/Core-Humanitarian-Standard_Portuguese.pdf

**Comment by GustavoDuregger** [comment]
Feito
Lançado versão 1.0.0-Alpha
https://github.com/HXL-CPLP/principios-e-padroes-humanitarios/releases/tag/v1.0.0-alpha

Site:

**Comment by GustavoDuregger** [comment]
Feito
Lançado versão 1.0.0-Alpha
https://github.com/HXL-CPLP/principios-e-padroes-humanitarios/releases/tag/v1.0.0-alpha

Site: https://hxl.etica.ai/principios-e-padroes-humanitarios/
Repositório:https://github.com/HXL-CPLP/principios-e-padroes-humanitarios
